### ISSUE TITLE
provide a license file for media & contents

### ISSUE THREAD

**Issue by dayne** [Bash-it/media#3]
If you don't provide a license file it leaves people not knowing how they can use the bash-it logo and other media files you are providing.

Recommend picking a creative commons license:
https://creativecommons.org/choose/

And adding the right one to a LICENSE file in the repo here with link in readme to the license picked.

My recommendation would be: [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)

**Comment by nwinkler** [comment]
Thanks for the recommendation/request!

@edubxb @nucliweb @tswicegood What do you guys think? A Creative Commons license for the logos - sounds right to me...

We also still have the open topic about a general license for Bash-it.

**Comment by nucliweb** [comment]
A CC license for the logos sounds right too for me.

👍
